# Generated by Django 5.1.3 on 2025-02-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agentinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('tier', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'agentinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Agentstats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_point', models.IntegerField(blank=True, null=True)),
                ('attack', models.IntegerField(blank=True, null=True)),
                ('defense', models.IntegerField(blank=True, null=True)),
                ('impact', models.IntegerField(blank=True, null=True)),
                ('crit_rate', models.IntegerField(blank=True, null=True)),
                ('crit_damage', models.IntegerField(blank=True, null=True)),
                ('anomaly_mastery', models.IntegerField(blank=True, null=True)),
                ('anomaly_proficiency', models.IntegerField(blank=True, null=True)),
                ('penetration_ratio', models.IntegerField(blank=True, null=True)),
                ('penetration_percentage', models.IntegerField(blank=True, null=True)),
                ('energy_regen', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'agentstats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Basestatsname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'basestatsname',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Constantmainstat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'constantmainstat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Constantsubstat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'constantsubstat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Discs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'discs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'element',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'faction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Passivestat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'passivestat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rolesubstat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rolesubstat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wengine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'wengine',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WengineAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'wengine_agent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wenginemainstats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wenginemainstats',
                'managed': False,
            },
        ),
    ]
