# Generated by Django 5.1.3 on 2025-02-03 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('tier', models.CharField(blank=True, max_length=1, null=True)),
                ('faction', models.CharField(blank=True, max_length=255, null=True)),
                ('element', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('health_point', models.IntegerField(blank=True, null=True)),
                ('attack', models.IntegerField(blank=True, null=True)),
                ('defense', models.IntegerField(blank=True, null=True)),
                ('impact', models.IntegerField(blank=True, null=True)),
                ('crit_rate', models.IntegerField(blank=True, null=True)),
                ('crit_damage', models.IntegerField(blank=True, null=True)),
                ('anomaly_mastery', models.IntegerField(blank=True, null=True)),
                ('anomaly_proficiency', models.IntegerField(blank=True, null=True)),
                ('penetration_ratio', models.IntegerField(blank=True, null=True)),
                ('penetration', models.IntegerField(blank=True, null=True)),
                ('energy_regen', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'agents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wenginesubstats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wenginesubstats',
                'managed': False,
            },
        ),
    ]
