# Generated by Django 5.1.3 on 2025-02-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_authgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discsinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disc_name', models.CharField(blank=True, max_length=255, null=True)),
                ('stat_name', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'discs_info',
                'managed': False,
            },
        ),
    ]
