# Generated by Django 5.1.3 on 2025-02-05 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_discsinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Possiblepositionstat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'possiblepositionstat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Possiblestats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'possible_stats',
                'managed': False,
            },
        ),
    ]
