# Generated by Django 5.1.3 on 2025-02-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_possiblepositionstat_possiblestats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('light_color', models.CharField(blank=True, max_length=12, null=True)),
                ('light_gradient', models.CharField(blank=True, max_length=12, null=True)),
                ('dark_gradient', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'db_table': 'colors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Constantsubstats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'constant_sub_stats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Possiblesubstats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'possible_sub_stats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wengineagentinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('tier', models.CharField(blank=True, max_length=1, null=True)),
                ('agent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('agent_nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('main_stat_name', models.CharField(blank=True, max_length=255, null=True)),
                ('main_stat_value', models.FloatField(blank=True, null=True)),
                ('main_stat_type', models.CharField(blank=True, max_length=10, null=True)),
                ('sub_stat_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_stat_value', models.FloatField(blank=True, null=True)),
                ('sub_stat_type', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'wengine_agent_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wengineinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('tier', models.CharField(blank=True, max_length=1, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('main_stat_name', models.CharField(blank=True, max_length=255, null=True)),
                ('main_stat_value', models.FloatField(blank=True, null=True)),
                ('main_stat_type', models.CharField(blank=True, max_length=10, null=True)),
                ('sub_stat_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_stat_value', models.FloatField(blank=True, null=True)),
                ('sub_stat_type', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'wengine_info',
                'managed': False,
            },
        ),
    ]
