# Generated by Django 5.1.3 on 2025-02-23 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_colors_constantsubstats_possiblesubstats_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentsStatsPerLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_level', models.CharField(blank=True, max_length=1, null=True)),
                ('agent_level', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'agents_stats_per_level',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Possiblesubstat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'possiblesubstat',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Agents',
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='Constantsubstats',
        ),
        migrations.DeleteModel(
            name='Discsinfo',
        ),
        migrations.DeleteModel(
            name='Possiblestats',
        ),
        migrations.DeleteModel(
            name='Possiblesubstats',
        ),
        migrations.DeleteModel(
            name='Rolesubstat',
        ),
        migrations.DeleteModel(
            name='Wengineagentinfo',
        ),
        migrations.DeleteModel(
            name='Wengineinfo',
        ),
    ]
