# Generated by Django 5.1.3 on 2025-02-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_constantsubstats_discsinfo_possiblestats_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCoreConstantStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'agent_core_constant_stat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Agentcorestats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('stat_id', models.IntegerField(blank=True, null=True)),
                ('stat_name', models.CharField(blank=True, max_length=255, null=True)),
                ('stat_type', models.CharField(blank=True, max_length=10, null=True)),
                ('stat_value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'agent_core_stats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConstantCoreStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'constant_core_stat',
                'managed': False,
            },
        ),
    ]
